import type { Disciplina, Atividade, TarefaPessoal, NotificacaoItem } from './types'

export const disciplinas: Disciplina[] = [
  {
    id: 'bd',
    nome: 'Banco de Dados',
    professor: 'Prof. Ricardo Silva',
    proximaAtividade: 'Prova 1 — 02/09',
    bgAccent: 'bg-blue-600',
    bgLight: 'bg-blue-50',
    textAccent: 'text-blue-600',
    borderAccent: 'border-blue-600',
  },
  {
    id: 'es',
    nome: 'Engenharia de Software',
    professor: 'Profª. Ana Lima',
    proximaAtividade: 'Projeto — 05/09',
    bgAccent: 'bg-indigo-600',
    bgLight: 'bg-indigo-50',
    textAccent: 'text-indigo-600',
    borderAccent: 'border-indigo-600',
  },
  {
    id: 'dw',
    nome: 'Desenvolvimento Web',
    professor: 'Prof. Carlos Mendes',
    proximaAtividade: 'Avaliação — 09/09',
    bgAccent: 'bg-violet-600',
    bgLight: 'bg-violet-50',
    textAccent: 'text-violet-600',
    borderAccent: 'border-violet-600',
  },
]

export const todasAtividades: Atividade[] = [
  {
    id: 1,
    tipo: 'PROVA',
    titulo: 'Prova 1',
    tituloLista: 'Prova 1 — Banco de Dados',
    disciplina: 'Banco de Dados',
    disciplinaId: 'bd',
    data: '02 SET',
    dataCompleta: '02/09/2026',
    horario: '19:00',
    local: 'Sala 204',
    conteudo: 'Modelo Relacional e SQL',
    professor: 'Prof. Ricardo Silva',
  },
  {
    id: 2,
    tipo: 'TRABALHO',
    titulo: 'Entrega do Projeto',
    tituloLista: 'Entrega do Projeto de Engenharia de Software',
    disciplina: 'Engenharia de Software',
    disciplinaId: 'es',
    data: '05 SET',
    dataCompleta: '05/09/2026',
    horario: '23:59',
    local: 'Plataforma Virtual / AVA',
    conteudo: 'Documento de Requisitos e Protótipo Navegável',
    professor: 'Profª. Ana Lima',
  },
  {
    id: 3,
    tipo: 'PROVA',
    titulo: 'Avaliação',
    tituloLista: 'Avaliação de Desenvolvimento Web',
    disciplina: 'Desenvolvimento Web',
    disciplinaId: 'dw',
    data: '09 SET',
    dataCompleta: '09/09/2026',
    horario: '19:00',
    local: 'Sala 102',
    conteudo: 'HTML5, CSS3, React e Tailwind CSS',
    professor: 'Prof. Carlos Mendes',
  },
  {
    id: 4,
    tipo: 'TRABALHO',
    titulo: 'Modelagem de Banco de Dados',
    tituloLista: 'Modelagem de Banco de Dados',
    disciplina: 'Banco de Dados',
    disciplinaId: 'bd',
    data: '15 SET',
    dataCompleta: '15/09/2026',
    horario: '23:59',
    local: 'Plataforma Virtual / AVA',
    conteudo: 'Diagrama Entidade-Relacionamento e Normalização (3FN)',
    professor: 'Prof. Ricardo Silva',
  },
]

export const proximasAtividades = todasAtividades.slice(0, 3)

export const tarefasIniciais: TarefaPessoal[] = [
  {
    id: 't1',
    titulo: 'Finalizar apresentação',
    data: '04/09/2026',
    dataFormatted: '04 SET',
    diaSemana: 'SEX',
    horario: '18:00',
    descricao: 'Elaborar os slides de apresentação do projeto acadêmico.',
    concluida: false,
  },
  {
    id: 't2',
    titulo: 'Revisar exercícios de Banco de Dados',
    data: '06/09/2026',
    dataFormatted: '06 SET',
    diaSemana: 'DOM',
    horario: '10:00',
    descricao: 'Resolver a lista de exercícios 3 para fixação de SQL.',
    concluida: false,
  },
  {
    id: 't3',
    titulo: 'Ler capítulo sobre modelo relacional',
    data: '30/08/2026',
    dataFormatted: '30 AGO',
    diaSemana: 'DOM',
    horario: '16:00',
    descricao: 'Capítulo 4 do livro de Banco de Dados de Elmasri & Navathe.',
    concluida: true,
    concluidaEm: '30/08',
  },
]

export const notificacoesIniciais: NotificacaoItem[] = [
  {
    id: 'n1',
    tipo: 'PRAZO_PROXIMO',
    titulo: 'Prova de Banco de Dados',
    mensagem: 'A Prova 1 de Banco de Dados será amanhã às 19:00.',
    tempo: 'Hoje • 08:00',
    lida: false,
    targetType: 'avaliacao',
    targetId: 1,
  },
  {
    id: 'n2',
    tipo: 'TRABALHO',
    titulo: 'Engenharia de Software',
    mensagem: 'O Projeto de Engenharia de Software vence em 2 dias.',
    tempo: 'Hoje • 09:30',
    lida: false,
    targetType: 'avaliacao',
    targetId: 2,
  },
  {
    id: 'n3',
    tipo: 'ALTERACAO_ACADEMICA',
    titulo: 'Desenvolvimento Web',
    mensagem: 'A data da Avaliação de Desenvolvimento Web foi alterada para 09/09 às 19:00.',
    tempo: 'Ontem • 17:20',
    lida: true,
    targetType: 'avaliacao',
    targetId: 3,
  },
  {
    id: 'n4',
    tipo: 'TAREFA',
    titulo: 'Revisar SQL',
    mensagem: 'Revisar SQL vence hoje às 20:00.',
    tempo: 'Hoje • 10:00',
    lida: true,
    targetType: 'tarefa',
    targetId: 't1',
  },
]


